-- #######################################################################################
-- AUTOGENERATED HYPRLAND LUA CONFIG.
-- #######################################################################################

require("config.monitors")
require("config.autostart")
require("config.environment")
require("config.theme")
require("config.inputs")
require("config.rules")
require("config.binds")
